### ISSUE TITLE
Pass the buck pods not created 

### ISSUE THREAD

**Issue by karanmagdani** [lucas-matt/auto-tracing-webhook#1]
Hello, 

I was trying out the guide [here](https://medium.com/opentracing/opentracing-on-kubernetes-get-yer-tracing-for-free-7a69cca03c8a) and I realized that the pod is not getting created with the following error on the replicaset. My Kubernetes is running using EKS on AWS. 

` Warning  FailedCreate  3m50s (x17 over 9m17s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "auto-tracing-mutating-webhook.default.svc.cluster.local": Post https://auto-tracing-mutating-webhook.default.svc:443/decorate?timeout=30s: x509: certificate has expired or is not yet valid`

**EDIT**
I can also verify that I see the same issue on minikube

**Comment by notmattlucas** [comment]
Hi, 

Yeah sorry, the certificate from the demo expired. I've updated it now.

Thanks

Matt
