### ISSUE TITLE
Error creating: Internal error occurred: failed calling webhook "auto-tracing-mutating-webhook.default.svc.cluster.local"

### ISSUE THREAD

**Issue by sudhanshud** [lucas-matt/auto-tracing-webhook#2]
I am getting below error:
Error creating: Internal error occurred: failed calling webhook "auto-tracing-mutating-webhook.default.svc.cluster.local": Post https://auto-tracing-mutating-webhook.default.svc:443/decorate?timeout=30s: x509: certificate has expired or is not yet valid

What is the caBundle certs. Is it Kubernetes certificate?

**Comment by baraschi** [comment]
@lucas-matt would it be possible to update the certificate? :) thanks a lot!

**Comment by notmattlucas** [comment]
@sudhanshud , @baraschi  - apologies for the delay in fixing this. Should be good now (for the next 10,000 days anyway ;))
