### ISSUE TITLE
auto tracing webhook not tracing deployment in the same namespace

### ISSUE THREAD

**Issue by akhilkochuveedu** [lucas-matt/auto-tracing-webhook#3]
Hi,

I'm using kubernetes **1.9** and have setup opentracing using auto-tracing-webhook following this page 
https://medium.com/opentracing/opentracing-on-kubernetes-get-yer-tracing-for-free-7a69cca03c8a
I've deployed **jaeger in default namespace** and **auto-tracing-webhook in test namespace** (**autotrace=enabled** labeled namespace). I also have other deployments running in the test namespace. These **deployments are labeled as  autotrace=enabled** but in my Jaeger UI, it's only showing 'jaeger-query' in the service name field. Both the jeager and auto-tracing-webhook pods are running without any error.
Why **Jaeger UI is not showing other services.** Am I missing something? Please help.

Thanks in advance.

**Comment by boystray** [comment]
how do you solve the problem “certificate has expired or is not yet valid”？

**Comment by notmattlucas** [comment]
@akhilkochuveedu , @boystray  - apologies for the delay in responding. The cert had expired. I've now updated to be valid for 10K days, so should be good now.

Thanks
