### ISSUE TITLE
Webhook or any other services won't start

### ISSUE THREAD

**Issue by konarskis** [lucas-matt/auto-tracing-webhook#5]
First, thank you for the effort with this tool!

I followed your Medium article, instructions in README (also regarding the certificates), but I keep having the issue that the webhook won't start, but also any other deployment won't start until the webhook is uninstalled form the cluster.

So I keep seeing 0/0 READY deployments in my k9s console with the following message when I describe the replica set:

```
replicaset-controller  Error creating: Internal error occurred: failed calling webhook "auto-tracing-mutating-webhook.default.svc.cluster.local": Post "https://auto-tracing-mutating-webhook.default.svc:443/decorate?timeout=30s": dial tcp 10.103.71.227:443: connect: connection refused
```

Do you have an idea what could be the issue?

Appreciate it!

**Comment by notmattlucas** [comment]
Hey, 

Sorry for the slow response.

I tried it on a Kubernetes 1.18 this morning to check it was still working.

Not sure what could be the issue with that error, looks like the webhook isn't running - I'd check the logs on that app.
